apps/restaurant/urls.py
from django.urls import path
from .views import (
    HomeView,
    AboutView,
    ServiceView,
    MenuView,
    BookingView,
    TeamView,
    TestimonialView,
    ContactView,
)

app_name = "restaurant"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("service/", ServiceView.as_view(), name="service"),
    path("menu/", MenuView.as_view(), name="menu"),
    path("booking/", BookingView.as_view(), name="booking"),
    path("team/", TeamView.as_view(), name="team"),
    path("testimonial/", TestimonialView.as_view(), name="testimonial"),
    path("contact/", ContactView.as_view(), name="contact"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('jahongir/', admin.site.urls),
    path('', include('apps.restaurant.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}About{% endblock %}
{% block content %}
    <div class="container-xxl py-5 bg-dark hero-header mb-5">
        <div class="container text-center my-5 pt-5 pb-4">
            <h1 class="display-3 text-white mb-3 animated slideInDown">Ma'lumotlar</h1>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center text-uppercase">
                    <li class="breadcrumb-item"><a href="{% url 'restaurant:home' %}">Bosh sahifa</a></li>
                    <li class="breadcrumb-item"><a href="#">Sahifalar</a></li>
                    <li class="breadcrumb-item text-white active" aria-current="page">Biz haqimizda</li>
                </ol>
            </nav>
        </div>
    </div>

    {% include 'section/about_section.html' %}
    
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">

<head>
    <meta charset="utf-8">
    <title>{{ home.name }}</title>
    <link rel="shortcut icon" href="{{ home.logo }}">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&family=Pacifico&display=swap"
          rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet"/>

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
<div class="container-xxl bg-white p-0">
    <!-- Spinner Start -->
    <div id="spinner"
         class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Yuklanyabdi...</span>
        </div>
    </div>
    <!-- Spinner End -->


    <!-- Navbar & Hero Start -->
    <div class="container-xxl position-relative p-0">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-4 px-lg-5 py-3 py-lg-0">
            <a href="{% url 'restaurant:home' %}" class="navbar-brand p-0">
                <div class="d-flex align-items-center">
                    <img src="/media/{{ home.logo }}" alt="logo" class="img-fluid" style="height: 50px;">
                    <h1 class="text-primary m-0">{{ home.name }}</h1>
                </div>
            </a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="fa fa-bars"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav ms-auto py-0 pe-4">
                    <a href="{% url 'restaurant:home' %}" class="nav-item nav-link active">Bosh sahifa</a>
                    <a href="{% url 'restaurant:service' %}" class="nav-item nav-link">Xizmatlar</a>
                    <a href="{% url 'restaurant:menu' %}" class="nav-item nav-link">Menyu</a>
                    <a href="{% url 'restaurant:contact' %}" class="nav-item nav-link">Bog'lanish</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Sahifalar</a>
                        <div class="dropdown-menu m-0">
                            <a href="{% url 'restaurant:about' %}" class="dropdown-item">Biz haqimizda</a>
                            <a href="{% url 'restaurant:team' %}" class="dropdown-item">Bizning jamoa</a>
                            <a href="{% url 'restaurant:testimonial' %}" class="dropdown-item">Mijozlar fikri</a>
                        </div>
                    </div>
                </div>
                <a href="{% url 'restaurant:booking' %}" class="btn btn-primary py-2 px-4">Joy bron qilish</a>
            </div>
        </nav>
    </div>
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            <p>{{ message }}</p>
        </div>
    {% endfor %}


    {% block content %}
    {% endblock %}

    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.0s">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-3 col-md-6">
                    <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Kompaniya</h4>
                    <a class="btn btn-link" href="{% url 'restaurant:about' %}">Biz haqimizda</a>
                    <a class="btn btn-link" href="{% url 'restaurant:contact' %}">Bog'lanish</a>
                    <a class="btn btn-link" href="{% url 'restaurant:booking' %}">Bron qilish</a>
                    {#                    <a class="btn btn-link" href="{% url 'restaurant:home' %}">Privacy Policy</a>#}
                    {#                    <a class="btn btn-link" href="{% url 'restaurant:home' %}">Terms & Condition</a>#}
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Kontaktlar</h4>
                    <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>{{ home.address }}</p>
                    <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>{{ home.phone }}</p>
                    <p class="mb-2"><i class="fa fa-envelope me-3"></i>{{ home.email }}</p>
                    <div class="d-flex pt-2">
                        <a class="btn btn-outline-light btn-social" href="{{ home.instagram }}"><i
                                class="fab fa-instagram"></i></a>
                        <a class="btn btn-outline-light btn-social" href="{{ home.telegram }}"><i
                                class="fab fa-telegram"></i></a>
                        <a class="btn btn-outline-light btn-social" href="{{ home.youtube }}"><i
                                class="fab fa-youtube"></i></a>
                        <a class="btn btn-outline-light btn-social" href="{{ home.facebook }}"><i
                                class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social" href="{{ home.twitter }}"><i
                                class="fab fa-twitter"></i></a>

                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Ish vaqtlari</h4>
                    {% for time in worktime %}
                        <h5 class="text-light fw-normal">{{ time.day }}</h5>
                        <p>{{ time.start_time }} - {{ time.end_time }}</p>
                    {% endfor %}
                </div>


                <div class="col-lg-3 col-md-6">
                    <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Yangiliklar</h4>
                    <p>Yangiliklardan xabardor bo'lish uchun elektron pochtangizni kiritib yuborish tugmasini
                        bosing.</p>
                    <form method="post">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            {{ form.useremail }}
                            <button type="submit" class="btn btn-primary">Yuborish</button>
                        </div>
                    </form>
                    <div class="position-relative mx-auto" style="max-width: 400px;">
                    </div>
                </div>


                <div class="container">
                    <div class="copyright">
                        <div class="row">
                            <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                                &copy; <a class="border-bottom" href="{% url 'restaurant:home' %}">{{ home.name }}</a>,
                                Barcha xizmatlar
                                litsenziyalangan.

                                <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                                Muallif <a class="border-bottom" href="https://github.com/JahongirHakimjonov"> Jahongir
                                Hakimjonov</a>
                            </div>
                            <div class="col-md-6 text-center text-md-end">
                                <div class="footer-menu">
                                    <a href="{% url 'restaurant:home' %}">Bosh sahifa</a>
                                    <a href="">Qo'llab & Quvvatlash xizmati</a>
                                    <a href="{% url 'restaurant:contact' %}">Yordam</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Footer End -- >

    <!/-- Back to Top -->
            <a href="" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
        </div>
    </div>
</div>


<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'lib/wow/wow.min.js' %}"></script>
<script src="{% static 'lib/easing/easing.min.js' %}"></script>
<script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
<script src="{% static 'lib/counterup/counterup.min.js' %}"></script>
<script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'lib/tempusdominus/js/moment.min.js' %}"></script>
<script src="{% static 'lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
<script src="{% static 'lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

<!-- Template Javascript -->
<script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/booking.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Joy bron qilish{% endblock %}
{% block content %}
    <div class="container-xxl py-5 bg-dark hero-header mb-5">
        <div class="container text-center my-5 pt-5 pb-4">
            <h1 class="display-3 text-white mb-3 animated slideInDown">Joy bron qilish</h1>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center text-uppercase">
                    <li class="breadcrumb-item"><a href="{% url 'restaurant:home' %}">Bosh sahifa</a></li>
                    <li class="breadcrumb-item"><a href="#">Sahifalar</a></li>
                    <li class="breadcrumb-item text-white active" aria-current="page">Joy bron qilish</li>
                </ol>
            </nav>
        </div>
    </div>

    {% include 'section/booking_section.html' %}
{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Contact{% endblock %}
{% block content %}
    <div class="container-xxl py-5 bg-dark hero-header mb-5">
        <div class="container text-center my-5 pt-5 pb-4">
            <h1 class="display-3 text-white mb-3 animated slideInDown">Biz bilan bog'lanish</h1>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center text-uppercase">
                    <li class="breadcrumb-item"><a href="#">Bosh sahifa</a></li>
                    <li class="breadcrumb-item"><a href="#">Sahifalar</a></li>
                    <li class="breadcrumb-item text-white active" aria-current="page">Bog'lanish</li>
                </ol>
            </nav>
        </div>
    </div>

    {% include 'section/contact_section.html' %}
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Bosh sahifa{% endblock %}
{% block content %}
    <div class="container-xxl py-5 bg-dark hero-header mb-5">
        <div class="container my-5 py-5">
            <div class="row align-items-center g-5">
                <div class="col-lg-6 text-center text-lg-start">
                    <h1 class="display-3 text-white animated slideInLeft">{{ home.title }}</h1>
                    <p class="text-white animated slideInLeft mb-4 pb-2">{{ home.description }}</p>
                    <a href="{% url 'restaurant:booking' %}"
                       class="btn btn-primary py-sm-3 px-sm-5 me-3 animated slideInLeft">Joy bron qilish</a>
                </div>
                <div class="col-lg-6 text-center text-lg-end overflow-hidden">
                    <img class="img-fluid" src="{% static 'img/hero.png' %}" alt="taom">
                </div>
            </div>
        </div>
        </div>
        </div>
    <!-- Navbar & Hero End -->

    {% include 'section/service_section.html' %}
    {% include 'section/about_section.html' %}
    {% include 'section/team_section.html' %}
    {% include 'section/testimonial_section.html' %}

{% endblock %}

templates/menu.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Menu{% endblock %}

{% block content %}
    <div class="container-xxl py-5 bg-dark hero-header mb-5">
        <div class="container text-center my-5 pt-5 pb-4">
            <h1 class="display-3 text-white mb-3 animated slideInDown">Taomlar ro'yxati</h1>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center text-uppercase">
                    <li class="breadcrumb-item"><a href="{% url 'restaurant:home' %}">Bosh sahifa</a></li>
                    <li class="breadcrumb-item"><a href="#">Sahifalar</a></li>
                    <li class="breadcrumb-item text-white active" aria-current="page">Menyu</li>
                </ol>
            </nav>
        </div>
    </div>

    {% include 'section/menu_section.html' %}

{% endblock %}

templates/service.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Service{% endblock %}
{% block content %}
    <div class="container-xxl py-5 bg-dark hero-header mb-5">
        <div class="container text-center my-5 pt-5 pb-4">
            <h1 class="display-3 text-white mb-3 animated slideInDown">Xizmatlarimiz</h1>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center text-uppercase">
                    <li class="breadcrumb-item"><a href="{% url 'restaurant:home' %}">Bosh sahifa</a></li>
                    <li class="breadcrumb-item"><a href="#">Sahifalar</a></li>
                    <li class="breadcrumb-item text-white active" aria-current="page">Xizmatlar</li>
                </ol>
            </nav>
        </div>
    </div>

    {% include 'section/service_section.html' %}
{% endblock %}

templates/team.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Team{% endblock %}
{% block content %}
    <div class="container-xxl py-5 bg-dark hero-header mb-5">
        <div class="container text-center my-5 pt-5 pb-4">
            <h1 class="display-3 text-white mb-3 animated slideInDown">Bizning Jamoamiz</h1>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center text-uppercase">
                    <li class="breadcrumb-item"><a href="{% url 'restaurant:home' %}">Bosh sahifa</a></li>
                    <li class="breadcrumb-item"><a href="#">Sahifalar</a></li>
                    <li class="breadcrumb-item text-white active" aria-current="page">Bizning jamoa</li>
                </ol>
            </nav>
        </div>
    </div>

    {% include 'section/team_section.html' %}
{% endblock %}

templates/testimonial.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Testimonial{% endblock %}
{% block content %}
    <div class="container-xxl py-5 bg-dark hero-header mb-5">
        <div class="container text-center my-5 pt-5 pb-4">
            <h1 class="display-3 text-white mb-3 animated slideInDown">Mijozlar fikri</h1>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center text-uppercase">
                    <li class="breadcrumb-item"><a href="{% url 'restaurant:home' %}">Bosh sahifa</a></li>
                    <li class="breadcrumb-item"><a href="#">Sahifalar</a></li>
                    <li class="breadcrumb-item text-white active" aria-current="page">Mijozlar fikri</li>
                </ol>
            </nav>
        </div>
    </div>

    {% include 'section/testimonial_section.html' %}
{% endblock %}